export const contactList = [
    {
      id: 1,
      name: "Damini Gour",
      profilePic: "/images/damini.jpg",
      lastText: "Have you subscribed The Indian Dev",
      lastTextTime: "12:58 PM",
    },
    {
      id: 2,
      name: "Rushikesh",
      profilePic: "/images/rushikesh.jpg",
      lastText: `I'm with @theindiandev`,
      lastTextTime: "12:45 PM",
    },
    {
      id: 3,
      name: "Sidharth Maximess",
      profilePic: "/images/sid.jpg",
      lastText: "Where is my Tesla?",
      lastTextTime: "12:30 PM",
    },
    {
      id: 4,
      name: "Reena Maximess",
      profilePic: "/images/reena.jpg",
      lastText: "Travelling to space",
      lastTextTime: "12:00 PM",
    },
    {
      id: 5,
      name: "IT ke Dhurandar",
      profilePic: "/images/it_ke.jpg",
      lastText: "https://youtu.be/spGQdrtfasI",
      lastTextTime: "12:58 PM",
    },
    {
      id: 6,
      name: "Yash",
      profilePic: "/images/yash.jpg",
      lastText: `kuthe ahe`,
      lastTextTime: "12:45 PM",
    },
    {
      id: 7,
      name: "Aditya",
      profilePic: "/images/aditya.jpg",
      lastText: "Where are you ??",
      lastTextTime: "12:30 PM",
    },
    {
      id: 8,
      name: "Jitu",
      profilePic: "/images/apple.jpg",
      lastText: "hiiii...",
      lastTextTime: "12:00 PM",
    },
  ];
  export const messagesList = [
    {
      id: 1,
      messageType: "TEXT",
      text: "Hey Man 😁",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 2,
      messageType: "TEXT",
      text: "how are you",
      senderID: 1,
      addedOn: "12:01 PM",
    },
    {
      id: 3,
      messageType: "TEXT",
      text: "All Good, What about you?",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 4,
      messageType: "TEXT",
      text: "I'm good as well",
      senderID: 1,
      addedOn: "12:00 PM",
    },
    {
      id: 5,
      messageType: "TEXT",
      text: "Great 😁",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 5,
      messageType: "TEXT",
      text: "Have you subscribed The Indian Dev ?",
      senderID: 1,
      addedOn: "12:00 PM",
    },
    {
      id: 5,
      messageType: "TEXT",
      text: "Have you subscribed The Indian Dev ?",
      senderID: 1,
      addedOn: "12:00 PM",
    },
    {
      id: 5,
      messageType: "TEXT",
      text: "Have you subscribed The Indian Dev ?",
      senderID: 1,
      addedOn: "12:00 PM",
    },
  ];